---
title: "iteration and listcols"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)

l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l

l$vec_numeric
l[[1]]
l[[1]][1:3]
```

```{r}
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

is.list(df)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

```{r}
output = vector("list", length = 4)
```

An example of a `for loop`

```{r}
for (i in 1:4) {
    
    output[[i]] = mean_and_sd(df[[i]])
    
}

output
```

```{r}
output = map(df, mean_and_sd)
output

output_median = map(df, median)
output_median

output_summary = map(df, summary)
output_summary

output = map_dfr(df, mean_and_sd)
output
```

```{r}
output = map(df, ~mean_and_sd(.x))
```

```{r}
read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5)

vec_urls

output = vector("list", length = 5)

for (i in 1:5) {
    
    output[[i]] = read_page_reviews(vec_urls[[i]])
    
}

output

output = map(vec_urls, read_page_reviews)
```

